<?xml version="1.0" encoding="utf-8"?><Database Name="FoodOrder" Class="FoodItemLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PETER-PC;Initial Catalog=FoodOrder;Integrated Security=True" SettingsObjectName="MvvmConceptWPF.Properties.Settings" SettingsPropertyName="FoodOrderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CategorisedItems" Member="CategorisedItems">
    <Type Name="CategorisedItem">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Category_CategorisedItem" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
      <Association Name="MenuItem_CategorisedItem" Member="MenuItem" ThisKey="ItemId" OtherKey="ItemId" Type="MenuItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Category" Member="Category1" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Category_CategorisedItem" Member="CategorisedItems" ThisKey="CategoryID" OtherKey="CategoryID" Type="CategorisedItem" />
    </Type>
  </Table>
  <Table Name="dbo.MenuItems" Member="MenuItems">
    <Type Name="MenuItem">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Price2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ChineseName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuID" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShortName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="MenuItem_CategorisedItem" Member="CategorisedItems" ThisKey="ItemId" OtherKey="ItemId" Type="CategorisedItem" />
    </Type>
  </Table>
  <Function Name="dbo.GetFoodItems" Method="GetFoodItems">
    <ElementType Name="GetFoodItemsResult">
      <Column Name="ItemId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FoodName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Price2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ChineseName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ItemCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuID" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShortName" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.UpdateFoodItem" Method="UpdateFoodItem">
    <Parameter Name="FoodName" Parameter="foodName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ItemPrice" Parameter="itemPrice" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="ItemId" Parameter="itemId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>